INSERT INTO CLIENTS (CODE, NAME) VALUES
('C001', 'MEDIA-SATURN'),
('C002', 'LEROY MERLIN'),
('C003', 'DECATHLON'),
('C004', 'TRADEINN'),
('C005', 'CARREFOUR'),
('C006', 'AUCHAN'),
('C007', 'TELEFONICA'),
('C008', 'SONY'),
('C009', 'LOREAL'),
('C010', 'CECOTEC');

INSERT INTO PRODUCTS (CLIENT_ID, NAME) VALUES
-- MEDIA-SATURN
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C001'), 'Smart TV 55 4K'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C001'), 'Portatil 15'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C001'), 'Aspirador robot'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C001'), 'Auriculares Bluetooth'),

-- LEROY MERLIN
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C002'), 'Taladro inalambrico'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C002'), 'Videoportero WiFi'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C002'), 'Camara seguridad WiFi'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C002'), 'Aspirador robot'),

-- DECATHLON
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C003'), 'Zapatillas running'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C003'), 'Reloj deportivo GPS'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C003'), 'Auriculares Bluetooth'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C003'), 'Smartwatch'),

-- TRADEINN
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C004'), 'Zapatillas running'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C004'), 'Reloj deportivo GPS'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C004'), 'Gafas natacion'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C004'), 'Smartwatch'),

-- CARREFOUR
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C005'), 'Smart TV 55 4K'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C005'), 'Aspirador robot'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C005'), 'Router WiFi'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C005'), 'Crema hidratante 50ml'),

-- AUCHAN
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C006'), 'Smart TV 55 4K'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C006'), 'Taladro inalambrico'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C006'), 'Aspirador robot'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C006'), 'Altavoz Bluetooth'),

-- TELEFONICA
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C007'), 'Router WiFi'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C007'), 'Smartphone 128GB'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C007'), 'Tarifa fibra 600Mb'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C007'), 'Repetidor WiFi'),

-- SONY
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C008'), 'Smart TV 55 4K'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C008'), 'Auriculares Bluetooth'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C008'), 'Altavoz Bluetooth'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C008'), 'Camara seguridad WiFi'),

-- LOREAL
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C009'), 'Crema hidratante 50ml'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C009'), 'Serum vitamina C 30ml'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C009'), 'Champu reparador 250ml'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C009'), 'Protector solar SPF50 50ml'),

-- CECOTEC
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C010'), 'Aspirador robot'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C010'), 'Freidora de aire 5L'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C010'), 'Robot de cocina'),
((SELECT ID_CLIENT FROM CLIENTS WHERE CODE='C010'), 'Cafetera espresso');

-- Equivalencias para tener ya ejemplos metidos
INSERT INTO EQUIVALENCES (PRODUCT_ID_A, PRODUCT_ID_B) VALUES
(1, 17),   -- Smart TV 55 4K (C001) <-> Smart TV 55 4K (C005)
(3, 37);   -- Aspirador robot (C001) <-> Aspirador robot (C010)
