DROP DATABASE IF EXISTS MINDEREST;
CREATE DATABASE IF NOT EXISTS MINDEREST;
USE MINDEREST;
CREATE TABLE CLIENTS (
    ID_CLIENT INT PRIMARY KEY AUTO_INCREMENT,
    CODE VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCTS (
    ID_PRODUCT INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INT,
    NAME VARCHAR(125) NOT NULL,

    UNIQUE (CLIENT_ID, NAME),

    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID_CLIENT)
);

CREATE TABLE EQUIVALENCES (
    ID_EQUIVALENCE INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID_A INT,
    PRODUCT_ID_B INT,

    UNIQUE (PRODUCT_ID_A, PRODUCT_ID_B),

    FOREIGN KEY (PRODUCT_ID_A) REFERENCES PRODUCTS(ID_PRODUCT),
    FOREIGN KEY (PRODUCT_ID_B) REFERENCES PRODUCTS(ID_PRODUCT)
);